/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.yajug.users.domain;

import javax.persistence.metamodel.SingularAttribute;


@javax.persistence.metamodel.StaticMetamodel
(value=org.yajug.users.domain.DomainObject.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Nov 04 22:29:01 CET 2012")
public class DomainObject_ {
    public static volatile SingularAttribute<DomainObject,Long> key;
}
