/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.yajug.users.domain;

import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;


@javax.persistence.metamodel.StaticMetamodel
(value=org.yajug.users.domain.Event.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Nov 04 22:29:01 CET 2012")
public class Event_ extends DomainObject_  {
    public static volatile SingularAttribute<Event,Date> date;
    public static volatile SingularAttribute<Event,String> description;
    public static volatile ListAttribute<Event,Member> participants;
    public static volatile SingularAttribute<Event,String> title;
}
