/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.yajug.users.domain;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;


@javax.persistence.metamodel.StaticMetamodel
(value=org.yajug.users.domain.Member.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Nov 04 22:29:01 CET 2012")
public class Member_ extends DomainObject_  {
    public static volatile SingularAttribute<Member,String> company;
    public static volatile SingularAttribute<Member,String> email;
    public static volatile SingularAttribute<Member,String> firstName;
    public static volatile SingularAttribute<Member,String> lastName;
    public static volatile ListAttribute<Member,Membership> memberships;
    public static volatile ListAttribute<Member,Role> roles;
}
