/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.yajug.users.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;


@javax.persistence.metamodel.StaticMetamodel
(value=org.yajug.users.domain.Membership.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Nov 04 22:29:01 CET 2012")
public class Membership_ extends DomainObject_  {
    public static volatile SingularAttribute<Membership,Integer> amount;
    public static volatile SingularAttribute<Membership,Event> event;
    public static volatile SingularAttribute<Membership,Member> member;
    public static volatile SingularAttribute<Membership,Date> paiementDate;
    public static volatile SingularAttribute<Membership,Integer> year;
}
